accounts/urls.py
from django.conf.urls import url
from . import views
from studentscorner import settings
from django.contrib.auth.views import login, password_change, password_change_done
from forms import MyAuthenticationForm


urlpatterns = [
	
	url(r'^register/$', views.register,{ 'template_name':'registration/register.html'},name="register"),
	url(r'^my_account/$', views.my_account,{ 'template_name':'registration/my_account.html'},name="my_account"),
	url(r'^order_details/(?P<order_id>[-\w]+)/$', views.order_details,{ 'template_name':'registration/order_details.html'},name="order_details"),
	url(r'^order_info/$', views.order_info,{ 'template_name':'registration/order_info.html'},name="order_info"),

]

urlpatterns += [
	url(r'^login/$',login,{'template_name': 'registration/login.html','authentication_form':MyAuthenticationForm},name="login"),
	url(r'^password_change/$',password_change,{'template_name': 'registration/password_change_form.html'},name="password_change"),
	url(r'^password_change/done/$',password_change_done,{'template_name': 'registration/password_change_done.html'},name="password_change_done"),
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.show_cart, {'template_name':'cart/cart.html'}, name="show_cart"),
]

catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index,{ 'template_name':'catalog/index.html'},name="index"),
	url(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category,{ 'template_name':'catalog/category.html'},name="show_category"),
	url(r'^product/(?P<product_slug>[-\w]+)/$', views.show_product,{ 'template_name':'catalog/product.html'},name="show_product"),
]

studentscorner/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include('preview.urls', namespace="preview")),
    url(r'^', include('catalog.urls', namespace="catalog")),
    url(r'^cart/', include('cart.urls',namespace="cart")),
    url(r'^checkout/', include('checkout.urls',namespace="checkout")),
    url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^accounts/', include('django.contrib.auth.urls',namespace="accounts")),
]

handler404 = 'catalog.views.file_not_found_404'

catalog/models.py
from __future__ import unicode_literals

from django.db import models

class Category(models.Model):
	name 			= models.CharField(max_length=50)
	slug 			= models.SlugField(max_length=50,unique=True,help_text="Unique value for product page URL, created from name.")
	description 	= models.TextField()
	is_active 		= models.BooleanField(default=True)
	meta_keywords 	= models.CharField("Meta Keywords",max_length=255,help_text="Comma-delimited set of SEO keywords for meta tag.")
	meta_description = models.CharField("Meta Description",max_length=255,help_text="Content for meta description tag.")
	created_at 		= models.DateTimeField(auto_now_add=True)
	updated_at 		= models.DateTimeField(auto_now=True)

	class Meta:
		db_table 	= 'categories'
		ordering 	= ['-created_at']
		verbose_name_plural = 'Categories'

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('catalog_category',(),{ 'category_slug':self.slug })


class Product(models.Model):
	name 			= models.CharField(max_length=255,unique=True)
	slug 			= models.SlugField(max_length=50,unique=True,help_text="Unique value for product page URL, created from name.")
	brand 			= models.CharField(max_length=50)
	sku 			= models.CharField(max_length=50)
	price 			= models.DecimalField(max_digits=9,decimal_places=2)
	old_price 		= models.DecimalField(max_digits=9,decimal_places=2,blank=True,default=0.00)
	image 			= models.CharField(max_length=50)
	is_active 		= models.BooleanField(default=True)
	is_bestseller 	= models.BooleanField(default=False)
	quantity 		= models.IntegerField()
	description 	= models.TextField()
	meta_keywords 	= models.CharField("Meta Keywords",max_length=255,help_text="Comma-delimited set of SEO keywords for meta tag.")
	meta_description = models.CharField("Meta Description",max_length=255,help_text="Content for meta description tag.")
	created_at 		= models.DateTimeField(auto_now_add=True)
	updated_at 		= models.DateTimeField(auto_now=True)
	categories 		= models.ManyToManyField(Category)

	class Meta:
		db_table 	= 'products'
		ordering 	= ['-created_at']

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('show_product',(),{ 'product_slug':self.slug })

	@property
	def sale_price(self):
		if self.old_price > self.price:
			return self.price
		else:
			return None

catalog/forms.py
from django import forms
from .models import *

class ProductAdminForm(forms.ModelForm):
	class Meta:
		model = Product
		exclude = ('created_at','updated_at',)

	def clean_price(self):
		if self.cleaned_data['price'] <= 0:
			raise forms.ValidationError('Price must be greater than zero.')
		return self.cleaned_data['price']
		

catalog/views.py
from django.shortcuts import render , get_object_or_404
from .models import *
from django.core import urlresolvers
from cart import cart
from django.http import HttpResponseRedirect
from cart.forms import ProductAddToCartForm
from cart.models import CartItem

def index(request,template_name='catalog/index.html'):
	page_title = "Food products for people ad for"
	categories = Category.objects.all()
	slide_products = []
	for category in categories:
		try:
			slide_products.append(category.product_set.latest('id'))
		except:
			print "DoesNotExist"
		

	context = {'page_title':page_title,'categories':categories,'slide_products':slide_products}
	return render(request,template_name,context)

def show_category(request,category_slug, template_name='catalog/catalog.html'):
	c = get_object_or_404(Category,slug=category_slug)
	products = c.product_set.all()
	page_title  = c.name 
	meta_keywords = c.meta_keywords
	meta_description = c.meta_description
	return render(request, template_name,{'page_title':page_title,'products':products,'c':c})

def show_product(request, product_slug, template_name='catalog/product.html'):
	p = get_object_or_404(Product, slug=product_slug)
	categories = p.categories.filter(is_active=True)
	page_title = p.name
	meta_keywords = p.meta_keywords
	meta_description = p.meta_description

	# evaluate the HTTP method
	if request.method == 'POST':
		postdata = request.POST.copy()
		form = ProductAddToCartForm(request, postdata)
		# cart_item = CartItem()
		# my_form = ProductAddToCartForm(request, request.POST, instance=cart_item)
		# check if posted data is valid 
		if form.is_valid():
			# add to cart and redirect to cart page
			cart.add_to_cart(request)

			# if test cookie worked, get rid of it
			if request.session.test_cookie_worked():
				request.session.delete_test_cookie()

			url = urlresolvers.reverse('cart:show_cart')
			return HttpResponseRedirect(url)
		# return render(request,'catalog/forerror.html',{'form':form})
	else:
		form = ProductAddToCartForm(request=request,label_suffix=':')

	# assign the hidden input the product slug
	form.fields['product_slug'].widget.attrs['value'] = p.slug

	# set the test cookie on our first GET request
	request.session.set_test_cookie()
	return render(request, template_name,{'page_title':page_title,'categories':categories,'p':p,'form':form})

catalog/templates/catalog/base.html
{% load catalog_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="{{ meta_description }}">
		<meta name="keywords" content="{{ meta_keywords }}">
    {% block title %} {% endblock %}
    {% block css %} {% endblock %}
    {% block js %} {% endblock %}
		
	</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'catalog:index' %}">Cornerwale</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'catalog:show_category' category_slug='books-media' %}">Books</a></li>
            <li><a href="{% url 'catalog:show_category' category_slug='electronics' %}">Electronics</a></li>
            <li><a href="{% url 'catalog:show_category' category_slug='auto-sports' %}">Sports</a></li>
            <li> 
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
              </form>
            </li>
            </ul>
              <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}

                  <li><a href="{% url 'accounts:login' %}?next={{ request.path }}">SignIn</a></li>
                {% else %}
                  <li><a href="#">Profile</a></li>
                {% endif %}
                <li role="presentation"><a href="{% url 'cart:show_cart' %}">Cart<span class="badge">{% cart_box request %}</span></a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                   
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    
                  </ul>
                </li>
              </ul>
        </div>
      </div>
    </nav>
    {% block site_wrapper %} {% endblock %}
    
  </body>

</html>

catalog/templates/catalog/catalog.html
{% extends "catalog/base.html" %}
{% load catalog_tags %}
{% load staticfiles %}

{% block title %}
	<title > {% if page_title %} {{ page_title }} {% endif %} - {{ site_name }} </title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'catalog/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'catalog/css/navbar-fixed-top.css' %}"/>
    <link rel="stylesheet" href="{% static 'catalog/css/carousel.css' %}"/>
    <link rel="stylesheet" href="{% static 'catalog/css/signin.css' %}"/>
    <link rel="stylesheet" href="{% static 'catalog/css/theme.css' %}"/>

{% endblock %}
	
{% block js %}
	<script type="text/javascript" src="{% static 'catalog/js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'catalog/js/bootstrap.js' %}"></script>
{% endblock %}



{% block site_wrapper %}
	<!-- <div class="cart_box">
		{% cart_box request %}
	</div> -->
	
	{% block content %} {% endblock %}
{% endblock %}

catalog/templates/catalog/category.html
{% extends "catalog/catalog.html" %}

{% load staticfiles %}

{% block title %}
	<title>{% if page_title %} {{ page_title }} {% endif %} - {{ site_name }}
	</title>
{% endblock %}

{% block content %}
	<div class="container">
		<h1>{{ c.name }}</h1>
		<div class="row">
		{% for p in products %}
		    <div class="col-md-4">
		    	{% with 'catalog/images/products/thumbnails/'|add:p.image as image_static %}
		    		<a href="{% url 'catalog:show_product' product_slug=p.slug %}">
		    			<img src="{% static image_static %}" class="img-thumbnail" alt="{{ p.name }}" /> 
		    		</a>
				{% endwith %}
				<br>
		    	<strong>{{ p.name }}</strong>
		    </div>
		    {% if forloop.counter|divisibleby:3 %}
		</div>
		<div class="row">
		    {% endif %}
		{% endfor %}
		</div>

		
		
	</div>
{% endblock %}

catalog/templates/catalog/forerror.html
{{ form }}

catalog/templates/catalog/index.html
{% extends "catalog/catalog.html" %}
{% load staticfiles %}

{% block title %}
<title>{% if page_title %} {{ page_title }} {% endif %} - {{ site_name }}</title>
{% endblock %}


{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						{% for i in slide_products %}
							{% if forloop.counter == 0 %}
								<li data-target="#myCarousel" data-slide-to="{{forloop.counter}}" class="active"></li>
							{% else %}
								<li data-target="#myCarousel" data-slide-to="{{forloop.counter}}"></li>
							{% endif %}
						{% endfor %}
					</ol>
					<div class="carousel-inner" role="listbox">
						{% for slide in slide_products %}
							{% if forloop.counter0 == 0 %}
								<div class="item active">
							{% else %}
								<div class="item">
							{% endif %}

								{% with 'catalog/images/products/main/'|add:slide.image as image_static %}
								<a href="{% url 'catalog:show_product' product_slug=slide.slug %}">
									<img class="first-slide" src="{% static image_static %}" alt="{{ slide.name }}" />
								</a>
								{% endwith %}
								<div class="container">
									<div class="carousel-caption">
										<a class="btn btn-lg btn-warning" href="{% url 'catalog:show_product' product_slug=slide.slug %}" role="button">Buy Now</a>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>

					<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
		</div>

		{% for category in categories %}
			<div class="page-header">
				<h1>{{ category }}</h1>
			</div>
			<div class="row">
				{% for product in category.product_set.values|slice:":4" %}
					<div class="col-md-3">
						{% with 'catalog/images/products/thumbnails/'|add:product.image as image_static %}
							<a href="{% url 'catalog:show_product' product_slug=product.slug %}">
								<img src="{% static image_static %}" class="img-thumbnail" alt="{{ product.name }}" /> 
							</a>
						{% endwith %}
					</div>
					{% endfor %}
			</div>
		{% endfor %}
	</div>

{% endblock %}

catalog/templates/catalog/product.html
{% extends "catalog/catalog.html" %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				{% with 'catalog/images/products/main/'|add:p.image as image_static %}
		    		<img src="{% static image_static %}" class="img-thumbnail" alt="{{ p.name }}" />
				{% endwith %}
		    	
			</div>
			<div class="col-md-8">
				{{ p.name }}
				Brand: <em>{{ p.brand }}</em>
				<br /><br />
				SKU: {{ p.sku }}
				<br />
				In categor{{ categories.count|pluralize:"y,ies" }}:
				{% for c in categories %}
				
				<a href="{% url 'catalog:show_category' category_slug=c.slug  %}">{{ c.name }}</a>
				{% if not forloop.last %}, {% endif %}
				{% endfor %}
				<br /><br />
				{% if p.sale_price %}
				Was: <del>$ {{ p.old_price }}</del>
				<br />
				Now: $ {{ p.price }}
				{% else %}
				Price: $ {{ p.price }}
				{% endif %}
				<br /><br />
				<form method="post" action="." class="form-signin">
					{% csrf_token %}
					 
					{{ form.as_p }}
					<br>
					<button class="btn  btn-success" type="submit" alt="Add To Cart">Add To Cart</button>
					
				</form>
				<div></div>
				<br /><br />
				<div><br /><br /></div>
				<h3>Product Description</h3>
				{{ p.description }}
				
				



			</div>
		<div>
	</div>

{% endblock %}